export default {
    FETCH: 'ALBUMS/ FETCH',
    UPDATE: 'ALBUMS/ UPDATE',
    ADD: 'ALBUMS/ ADD',
    REMOVE: 'ALBUMS/ REMOVE',
    ADD_RELATED_TRACKS: 'ALBUMS/ ADD RELATED TRACKS',
    REMOVE_RELATED_TRACKS: 'ALBUMS/ REMOVE RELATED TRACKS'
};